version: '3'
services:
    web:
        build: ./docker/nginx
        ports:
            - "8080:80"
        volumes:
            - "./www:/var/www/project/"
        working_dir: "/var/www/project/"
    php:
        build: ./docker/php
        working_dir: "/var/www/project/"
        volumes:
            - "./www:/var/www/project/"
        env_file:
            - ./blackfire_client.env
        restart: always
    blackfire:
        image: blackfire/blackfire
        env_file:
            - ./blackfire_server.env
    mariadb:
        image: mariadb:latest
        restart: always
        volumes:
            - "db-data:/var/lib/mysql"
        ports:
            - "3306:3306"
        environment:
            - "MYSQL_ROOT_PASSWORD=r00tSql"
    elasticsearch_head:
        build: ./docker/elasticsearch_head
        ports:
            - "9100:9100"
    elasticsearch_master:
        build: ./docker/elasticsearch
        ports:
            - "9200:9200"
        environment:
            - cluster.name=mycluster
            - node.master=true
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    elasticsearch_slave:
        image: elasticsearch:latest
        environment:
            - cluster.name=mycluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - UNICAST_HOSTS=elasticsearch_master
            - "discovery.zen.ping.unicast.hosts=elasticsearch_master"
    rabbitmq_master:
        image: bijukunjummen/rabbitmq-server
        hostname: rabbitmq_master
        ports:
            - "15672:15672"
    rabbitmq:
        image: bijukunjummen/rabbitmq-server
        environment:
            - CLUSTERED=true
            - CLUSTER_WITH=rabbitmq_master

volumes:
    db-data:

