version: '2'
services:
    web:
        build: ./docker/nginx
        ports:
            - "8080:80"
        volumes_from:
            - data
        volumes:
            - "./www:/var/www/project/"
        working_dir: "/var/www/project/"
    php:
        build: ./docker/php
        working_dir: "/var/www/project/"
        volumes_from:
            - data
        volumes:
            - "./www:/var/www/project/"
        env_file:
            - ./blackfire_client.env
        restart: always
    blackfire:
        image: blackfire/blackfire
        env_file:
            - ./blackfire_server.env
    mariadb:
        image: mariadb:latest
        restart: always
        volumes_from:
            - data
        ports:
            - "3306:3306"
        environment:
            - "MYSQL_ROOT_PASSWORD=r00tSql"
    elasticsearch_master:
        build: ./docker/elasticsearch
        command: "elasticsearch -Des.cluster.name=mycluster -Des.node.master=true -Des.node.data=false"
        environment:
            - ES_HEAP_SIZE=512m
        ports:
            - "9200:9200"
    elasticsearch:
        image: elasticsearch:latest
        command: "elasticsearch -Des.cluster.name=mycluster -Des.discovery.zen.ping.unicast.hosts=elasticsearch_master"
        environment:
            - ES_HEAP_SIZE=2g
    rabbitmq_master:
        image: bijukunjummen/rabbitmq-server
        hostname: rabbitmq_master
        ports:
            - "15672:15672"
    rabbitmq:
        image: bijukunjummen/rabbitmq-server
        environment:
            - CLUSTERED=true
            - CLUSTER_WITH=rabbitmq_master
    data:
        build: ./docker/data
        volumes:
            - /var/lib/mysql
            - /var/www/project


